### ISSUE TITLE
かんたんな使用例があると良いと思います

### ISSUE THREAD

**Issue by ichimomo** [JK-junkin/gakkai_FO202111#30]
特に，Rmdとgitについては，実際の画面のスクショとかを貼ったりして，簡単な使い方の例があると良いかなと思いました

とくにRmdについては，example.Rmdかなんかのリンクを貼れれば，それをＰＣにダウンロードしてもらい，RStudioで実行してもらって実感してもらう，という手順なんかも紹介できるかなと，，

**Comment by akimanabe** [comment]
突貫工事で作ってPushしときますね！

**Comment by JK-junkin** [comment]
htmlかPDFフォーマットで、計算部分だけで構いません！よろしくお願いいたします。:bow:

**Comment by akimanabe** [comment]
一応たたき台はつくったのでCloseします
